version: '3'
services:

  frontend:
    build: ./front
    image: ts-app
    container_name: ts-app
    environment:
      - NODE_ENV=development
    volumes:
      - ./front/frontend:/usr/src/app
    ports:
      - '3000:3000'
    tty: true

  db:
    platform: linux/x86_64
    image: mysql/mysql-server:latest
    container_name: mysql_host 
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: postapp  
      MYSQL_USER: docker  
      MYSQL_PASSWORD: docker  
      TZ: 'Asia/Tokyo'  
    volumes:
      - ./db/data:/var/lib/mysql  
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf  
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command: 
      mysqld --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci 
      --default-authentication-plugin=mysql_native_password
